user:
  name:
    min_length: 1
    max_length: 50
  email:
    max_length: 255
    valid_regex: '\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z'
pagy:
    items: 10
gravatar:
    size: 70

micropost:
  content:
    max_length: 140

image:
  max_width: 200
  max_height: 200

digit_two: 2

digit_five: 5
